[package]
name = "sappix"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = { version = "0.30.1", features = ["core-simd", "nostd-libm"] }

[build-dependencies]
cc = "1.2.18"

[dev-dependencies]
gif = { version = "0.13.1", features = ["raii_no_panic"] }
